export enum SOCKET_EVENTS {
    INITIAL_SETUP = "INITIAL_SETUP",
  
    JOIN_CHAT = "JOIN_CHAT",
    JOIN_GLOBAL = "JOIN_GLOBAL",
    LEAVE_CHAT = "LEAVE_CHAT",
    JOIN_CHATS_LIST = "JOIN_CHATS_LIST",
    LEAVE_CHATS_LIST = "LEAVE_CHATS_LIST",
  
    MESSAGE = "MESSAGE",
    MESSAGE_READ = "MESSAGE_READ",
    MESSAGE_DELETED = "MESSAGE_DELETED",
    TYPING = "TYPING",
    PARTNER_JOINED = "PARTNER_JOINED",
    PARTNER_LEFT = "PARTNER_LEFT",
  
    CONVERSATION_UPDATE = "CONVERSATION_UPDATE",
    CONVERSATION_DELETED = "CONVERSATION_DELETED",
    CONVERSATION_DECREASE_UNREAD = "CONVERSATION_DECREASE_UNREAD",
    CONVERSATION_INCREASE_UNREAD = "CONVERSATION_INCREASE_UNREAD",
  
    OFFER_DECLINED = "OFFER_DECLINED",
    OFFER_ACCEPTED = "OFFER_ACCEPTED",
  }
  export enum MESSAGE_TYPE {
    TEXT = "TEXT",
    IMAGE = "IMAGE",
  }